language: python
python:
  - 3.6 
before_install:
  - sudo apt-get update
install:
  - pip3 install .
  - pip3 install -r requirements.txt
  - pip3 install python-coveralls 
script:
  - nosetests  --with-coverage --cover-package=mu
after_success:
  - coveralls
